name: kalakriti_2_0
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  http: ^1.2.1
  firebase_storage: ^13.0.1
  firebase_auth: ^6.0.2
  firebase_auth_web: ^6.0.2
  firebase_storage_web: ^3.10.19
  pdf: 3.10.7
  path_provider: 2.1.1
  share_plus: ^12.0.0
  qr_flutter: 4.1.0
  url_launcher: ^6.3.2
  js: ^0.7.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/